### PR TITLE
Ubuntu 20.04 fix

### PR DESCRIPTION
**Pull request by JLA4444**
This will fix install issues for Ubuntu Server 20.04

The python-docker lib is not available using apt and must be installed with python-pip

### CODE REVIEW

**Comment by spantaleev** [comment]
Maybe it's called `python3-docker` there?

See how the Ansible playbook does it - https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-base/tasks/server_base/setup_debian.yml

We may then avoid installing via `pip`, assuming `ansible_python_interpreter` is set correctly.

**Comment by JLA4444** [comment]
You where correct. Now i changed it to just install python3-docker instead of python-docker.

I thought i tried to search for that...

**Comment by spantaleev** [comment]
Isn't new Debian affected as well? I think we can have code that works for both Debian and Ubuntu, by targeting `when: ansible_os_family == 'Debian'` and then not hardcode the package name but use `"python{{'3' if ansible_python.version.major == 3 else ''}}-docker"` like seen here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-base/tasks/server_base/setup_debian.yml

**Comment by JLA4444** [comment]
Ok now I get what you mean. I am a HW engineer so I lack some SW thinking.

Have you tried this on latest Debian server or should I try it?

I will give it a try on ubuntu 20.04 server

**Comment by spantaleev** [comment]
The code used on the matrix playbook is surely tested on latest Debian, so we can just use it as is.

**Comment by JLA4444** [comment]
The smart solution worked.
Is there anything else i need to do?

**Comment by spantaleev** [comment]
Looks great! Thanks! :+1:

**Pull request merged**
