### PR TITLE
Add ability to mount local directorys in the docker container

### PR DESCRIPTION
**Pull request by JokerGermany**
This pull request add the ability to add local directorys of the server as external storage.

### CODE REVIEW

**Comment by spantaleev** [comment]
Thanks for contributing this!

It's better to do it using some `nextcloud_container_additional_volumes` variable though. See how we do it for Matrix:

- [defining the variable in defaults/main.yml](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/38027e72f6d541f46991eec4ea4ff6d40ae4aa90/roles/matrix-synapse/defaults/main.yml#L296-L304)
- [making use of it in the `.service` template](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/38027e72f6d541f46991eec4ea4ff6d40ae4aa90/roles/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2#L57-L59)

**Comment by JokerGermany** [comment]
Thanks for the feedback
What i don't understand, when i use a similar approach:
```
{% for mount in nextcloud_container_additional_mounts %}
--mount {{ mount }} \
{% endfor %}
```
I get an empty line when the variable is not set?!?

Why?

(I wanted to use mount because it's recommend)

**Comment by JokerGermany** [comment]
Now it's working, but i needed a if condition...

**Comment by JokerGermany** [comment]
fixes #4

**Comment by spantaleev** [comment]
If you had defined `nextcloud_container_additional_mounts` as `nextcloud_container_additional_mounts: []` (explicit array, instead of `null`), you would not need an `if` condition. It would both be clearer to the user that this variable needs to contain a list (although your comment does say so), and clear to your other logic that this variable is **always** a list that can be iterated.

----

Our `_additional_volumes` variables are more structured. Looks like with your `_mounts` variable, you've gone for "I'll just pass a list of `--mount` strings".

This reminds me of the `_container_extra_arguments` variables we have in the Matrix roles, which allow for passing any additional container arguments. You'd just need `--mount` or `-v` prefixes for mounting volumes, but it works the same way.

**Comment by JokerGermany** [comment]
> If you had defined `nextcloud_container_additional_mounts` as `nextcloud_container_additional_mounts: []` (explicit array, instead of `null`), you would not need an `if` condition.

I could swear i tested this ... 
thanks!

**Comment by spantaleev** [comment]
Thanks! :+1:

**Comment by JokerGermany** [comment]
> This reminds me of the `_container_extra_arguments` variables we have in the Matrix roles, which allow for passing any additional container arguments. You'd just need `--mount` or `-v` prefixes for mounting volumes, but it works the same way.

Yeah, the `_container_extra_arguments` variable is fine for additional fine tuning, but imagine this
mounts


> Our _additional_volumes variables are more structured. Looks like with your _mounts variable, you've gone for "I'll just pass a list of --mount strings".

I first made it like the volumes variable, but then i didn't see much benefits. The Source code is more complicated if you want to give the user all options
```
{% for mount in nextcloud_container_additional_mounts %}
--mount type={{ mount.type }},source={{ mount.src }},target={{ mount.dst }}{% if mount.options %},{{ mount.options }}{% endif %} \
{% endfor %}
```

And the input would be:
`{"type": "bind|volume|tmpfs", "src": "/outside", "dst": "/inside", "options": "readonly,bind-propagation=slave"}`

I didn't saw a benefit of this "more structured" way and thought about KISS...

**Pull request merged**
